### ISSUE TITLE
Lazy Initialization of Initial connection

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-temporal#70]
Should the microservice start up if Temporal is not available and keep trying?  According to Temporal docs this is not built in out of the box and you need to write a wrapper.

cc @tmulle

We could then add a HealthCheck that gets added to to Quarkus to signal Liveness and Readiness.

**Comment by rmanibus** [comment]
What is the current behavior with jdbc if the DB is not available?

**Comment by melloware** [comment]
I have to test both the db being down as well as temporal being unavailable completely.

**Comment by melloware** [comment]
Oh you mean in general a normal db app if the db is down. Good question I have to try it

**Comment by rmanibus** [comment]
yes in general

**Comment by tmulle** [comment]
I'm fine with that, I could see both ways.

In my case I have a REST endpoint and Temporal integration in one of my services. Technically, the REST endpoint doesn't need Temporal to be started since it doesn't do anything but call a DB. The temporal integration in that same service DOES need it to connect so it can process the workflows.

So, does it make sense to fail the whole thing if both aren't available? Maybe... but if we had auto-retry to temporal then we could startup and retry in the background. The service would just not process any temporal messages until it connected.

But if Quarkus fails on DB startup, then maybe we just follow that.

I know OIDC integration won't fail, it will just say "OIDC server not available...will try on first attempt" 

So, it seems to be up to the developer of the extension
